### ISSUE TITLE
Sushi: error Structure Definition http://hl7.no/fhir/StructureDefinition/no-basis-Patient is missing a snapshot. Snapshot is required for import. (00:00.378 / 00:19.121, 21Mb)

### ISSUE THREAD

**Issue by rockphotog** [HL7Norway/LMDI#10]
```
# TODO Sushi: error Structure Definition http://hl7.no/fhir/StructureDefinition/no-basis-Patient is missing a snapshot. Snapshot is required for import. (00:00.378 / 00:19.121, 21Mb)
```

https://github.com/HL7Norway/LMDI/blob/6751f0190e1e6b9f2fd25591ff5c6789e2147de2/LMDI/sushi-config.yaml#L23

**Comment by rockphotog** [comment]
Ka du tru, @thomiz ?

Jeg tror scriptet laster ned no-basis v2.1.1, mens jeg har referert til 2.2.0?

**Comment by thomiz** [comment]
For å si det sånn, det å inkludere no-basis i fsh prosjektere er et h***. Det er fordi SIMPLIFIER nekter å lage snapshots og man derfor må gjøre jobben med å skaffe snapshots manuelt. [test-fsh](https://github.com/thomiz/test-IG/tree/master/igs/test-fsh) IG'en viser hvordan dette kan gjøres på en veldig tungvint måte, med modifisering av action script og et eget [script](https://github.com/thomiz/test-IG/blob/master/install-no-basis-220-snapshot.sh) for kopi av no-basis snapshots til riktig sted inni den virtuelle maskinen som bygger IG'en hver gang IG skal bygges. 

Såvidt jeg vet vil problemet forsvinne hvis man bruker SUSHI på no-basis også. Mange velger heller å ta ned no-basis ressursene som en del av den IG'en man bygger, jeg tror [AuditEvent](https://github.com/HL7Norway/AuditEvent/tree/main/AuditEvent/input/fsh) gjorde noe sånt, men de skulle bare ha navnene mens de utviklet siden AuditEvent blir en del av no-basis til slutt...

**Comment by rockphotog** [comment]
Vi får ikke gjort noe med denne på nåværende tidspunkt.

**Comment by rockphotog** [comment]
:-(
